replicaCount: 1

imageAuthor:
  repository: jerkyface/mgnl-author
  pullPolicy: Always
  tag: "mgnl"

imagePublic:
  repository: jerkyface/mgnl-public
  pullPolicy: Always
  tag: "mgnl"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  name: http
  port: 8080
  targetPort: 8080

services:
  - name: author
    image:
      repository: jerkyface/mgnl-author
      tag: latest
  - name: public
    image:
      repository: jerkyface/mgnl-public
      tag: latest

resources:
  limits:
    memory: 2000Mi
  requests:
    cpu: 500m
    memory: 1000Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }


# Replaced with liveness after successful startup
# Supported for 1.16 (alpha). Needs to be enabled per Feature Gates.
# https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#using-a-feature
# https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#startup_probe
# TODO: enable this on the cluster and tighten the liveness probe!
startupProbe: { }
#  httpGet:
#    path: /.rest/status
#    port: http
#  failureThreshold: 30
#  periodSeconds: 6

env:
  author:
    - name: JAVA_OPTS
      # WARNING: Glob patterns are expanded.
      # Make sure to quote them if you don't want pattern expansion before magnolia is started
      value: >-
        -Dmagnolia.bootstrap.authorInstance=true
        -Dmagnolia.update.auto=true
        -Dmagnolia.home=/opt/magnolia
  public:
    - name: JAVA_OPTS
      value: >-
        -Dmagnolia.bootstrap.authorInstance=false
        -Dmagnolia.update.auto=true
        -Dmagnolia.home=/opt/magnolia