
# author
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "magnolia.fullname" . }}-author
  labels:
    {{- include "magnolia.labels" . | nindent 4 }}-author
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "magnolia.selectorLabels" . | nindent 6 }}-author
  serviceName: {{ include "magnolia.fullname" . }}-author-headless
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "magnolia.selectorLabels" . | nindent 8 }}-author
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-author
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imageAuthor.repository }}:{{ .Values.imageAuthor.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageAuthor.pullPolicy }}
          env:
            {{- toYaml .Values.env.author | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: magnolia-home
              mountPath: /opt/magnolia
            - name: mounted-config
              mountPath: /usr/local/config/repo-conf/jackrabbit-bundle-postgres-search.xml
              subPath: jackrabbit-bundle-postgres-search.xml
      volumes:
        - name: mounted-config
          configMap:
            name: {{ template "magnolia.fullname" . }}-author
        - name: magnolia-home
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

# public
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "magnolia.fullname" . }}-public
  labels:
    {{- include "magnolia.labels" . | nindent 4 }}-public
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "magnolia.selectorLabels" . | nindent 6 }}-public
  serviceName: {{ include "magnolia.fullname" . }}-public-headless
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "magnolia.selectorLabels" . | nindent 8 }}-public
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-public
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imagePublic.repository }}:{{ .Values.imagePublic.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePublic.pullPolicy }}
          env:
            {{- toYaml .Values.env.public | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: mounted-config
              mountPath: /usr/local/tomcat/config/repo-conf/jackrabbit-bundle-postgres-search.xml
              subPath: jackrabbit-bundle-postgres-search.xml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: mounted-config
          configMap:
            name: {{ template "magnolia.fullname" . }}-public
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}